package cli

import (
	"context"
	"fmt"
	"path/filepath"
	"sort"

	"github.com/jackhodkinson/schemata/internal/app"
	"github.com/jackhodkinson/schemata/internal/config"
	"github.com/jackhodkinson/schemata/internal/db"
	"github.com/jackhodkinson/schemata/internal/migration"
	"github.com/jackhodkinson/schemata/pkg/schema"
	"github.com/spf13/cobra"
)

var fixExtTarget string

var fixExtensionsCmd = &cobra.Command{
	Use:   "extensions",
	Short: "Generate a migration for extensions not created by any existing migration",
	Long: `Detect extensions installed on the target database that are not created by any
existing migration, and generate a new migration to create them.

This is useful when adopting schemata with an existing migrations directory where
extensions were installed outside of migrations (by a DBA, cloud provider, or
manual setup). After running this command, the migration directory is
self-contained and can build the database from scratch.

Examples:
  schemata fix extensions
  schemata fix extensions --target prod`,
	RunE: runFixExtensions,
}

func init() {
	fixCmd.AddCommand(fixExtensionsCmd)
	fixExtensionsCmd.Flags().StringVar(&fixExtTarget, "target", "", "Target database (required if multiple targets configured)")
}

func runFixExtensions(cmd *cobra.Command, args []string) error {
	ctx := context.Background()
	service := app.NewService(allowCascade)

	cfg, err := config.Load(cfgFile)
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Determine target connection
	var targetConn *config.DBConnection
	if cfg.Target != nil {
		if fixExtTarget != "" {
			return fmt.Errorf("--target flag specified but config only has single target")
		}
		targetConn = cfg.Target
	} else if cfg.Targets != nil {
		if fixExtTarget == "" {
			return fmt.Errorf("multiple targets configured, must specify --target flag")
		}
		conn, exists := cfg.Targets[fixExtTarget]
		if !exists {
			return fmt.Errorf("target '%s' not found in config", fixExtTarget)
		}
		targetConn = &conn
	} else {
		return fmt.Errorf("no target database configured")
	}

	// Connect to target to discover installed extensions
	targetPool, err := db.Connect(ctx, targetConn)
	if err != nil {
		return fmt.Errorf("failed to connect to target: %w", err)
	}
	defer targetPool.Close()

	catalog := db.NewCatalog(targetPool)
	installedObjects, err := catalog.ExtractExtensions(ctx)
	if err != nil {
		return fmt.Errorf("failed to extract extensions from target: %w", err)
	}

	installedNames := make(map[string]bool, len(installedObjects))
	for _, obj := range installedObjects {
		ext := obj.(schema.Extension)
		installedNames[ext.Name] = true
	}

	if len(installedNames) == 0 {
		fmt.Println("No extensions found on target database")
		return nil
	}

	// Scan existing migrations for CREATE EXTENSION statements
	migrations, err := service.ScanMigrations(cfg.Migrations.GetDir(), cfg.Migrations.GetFormat())
	if err != nil {
		return err
	}

	managedExtensions, err := migration.FindExtensionsInMigrations(migrations)
	if err != nil {
		return fmt.Errorf("failed to scan migrations for extensions: %w", err)
	}

	managedSet := make(map[string]bool, len(managedExtensions))
	for _, name := range managedExtensions {
		managedSet[name] = true
	}

	// Find unmanaged extensions
	var unmanaged []string
	for name := range installedNames {
		if !managedSet[name] {
			unmanaged = append(unmanaged, name)
		}
	}
	sort.Strings(unmanaged)

	if len(unmanaged) == 0 {
		fmt.Println("All installed extensions are already created by existing migrations")
		return nil
	}

	// Determine version (before earliest migration)
	version := migration.VersionBefore(earliestVersion(migrations))

	// Build migration SQL
	var sql string
	sql += "-- Generated by schemata fix extensions\n"
	sql += "-- This migration creates extensions that were previously installed outside of migrations.\n"
	for _, name := range unmanaged {
		sql += fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s;\n", name)
	}

	// Write migration file
	gen := migration.NewGenerator(cfg.Migrations.GetDir())
	mig, err := gen.GenerateWithVersion(version, "add-extensions", sql)
	if err != nil {
		return fmt.Errorf("failed to create migration: %w", err)
	}

	relPath, err := filepath.Rel(".", mig.FilePath)
	if err != nil {
		relPath = mig.FilePath
	}

	fmt.Printf("\nFound extensions on target not created by any migration:\n")
	for _, name := range unmanaged {
		fmt.Printf("  - %s\n", name)
	}
	fmt.Printf("\nCreated migration: %s\n", relPath)
	fmt.Printf("  (ordered before earliest migration via version %s)\n", version)

	return nil
}

func earliestVersion(migrations []migration.Migration) string {
	if len(migrations) == 0 {
		return ""
	}
	earliest := migrations[0].Version
	for _, m := range migrations[1:] {
		if m.Version < earliest {
			earliest = m.Version
		}
	}
	return earliest
}
