//go:build integration

package cli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jackhodkinson/schemata/internal/db"
	"github.com/jackhodkinson/schemata/internal/differ"
	"github.com/jackhodkinson/schemata/internal/objectmap"
	"github.com/jackhodkinson/schemata/internal/parser"
	"github.com/jackhodkinson/schemata/internal/planner"
	"github.com/stretchr/testify/require"
)

func TestIntegration_SequenceDumpParsesReappliesAndRoundTripsExactly(t *testing.T) {
	ctx := context.Background()
	pool := connectIntegrationPool(t)
	t.Cleanup(pool.Close)

	reset := func() {
		t.Helper()
		_, err := pool.Exec(ctx, `
			DROP SCHEMA IF EXISTS public CASCADE;
			CREATE SCHEMA public;
			GRANT ALL ON SCHEMA public TO postgres;
			GRANT ALL ON SCHEMA public TO public;
		`)
		require.NoError(t, err)
	}
	reset()
	t.Cleanup(reset)

	_, err := pool.Exec(ctx, `
		CREATE TABLE public.identity_items (
			ascending_id integer GENERATED ALWAYS AS IDENTITY (
				SEQUENCE NAME public.custom_identity_ids
				START WITH 41 INCREMENT BY 7 CACHE 3 CYCLE
			),
			descending_id integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1)
		);

		CREATE SEQUENCE public.explicit_item_ids AS integer
			START WITH 11 INCREMENT BY 3 CACHE 7 CYCLE;
		CREATE TABLE public.explicit_items (
			id integer DEFAULT nextval('public.explicit_item_ids'::regclass)
		);
		ALTER SEQUENCE public.explicit_item_ids OWNED BY public.explicit_items.id;
		COMMENT ON SEQUENCE public.explicit_item_ids IS 'preserved sequence';
	`)
	require.NoError(t, err)

	originalObjects, err := db.NewCatalog(pool).ExtractAllObjects(ctx, []string{"public"}, nil)
	require.NoError(t, err)
	originalMap, err := objectmap.Build(originalObjects)
	require.NoError(t, err)

	dumpPath := filepath.Join(t.TempDir(), "schema.sql")
	_, err = writeDumpSingleFile(dumpPath, originalObjects, planner.NewDDLGenerator())
	require.NoError(t, err)
	dumpSQL, err := os.ReadFile(dumpPath)
	require.NoError(t, err)
	require.Contains(t, string(dumpSQL), `SEQUENCE NAME "public"."custom_identity_ids"`)
	require.Contains(t, string(dumpSQL), `INCREMENT BY -1`)
	assertOwnedSequenceDumpOrderForNames(t, string(dumpSQL), "explicit_item_ids", "explicit_items")

	parsedDump, err := parser.NewParser().ParseFile(dumpPath)
	require.NoError(t, err, "sequence dump must parse:\n%s", dumpSQL)
	parsedDiff, err := differ.NewDiffer().Diff(parsedDump, originalMap)
	require.NoError(t, err)
	require.True(t, parsedDiff.IsEmpty(), "parsed sequence dump must match source: creates=%v drops=%v alters=%v", parsedDiff.ToCreate, parsedDiff.ToDrop, parsedDiff.ToAlter)

	reset()
	_, err = pool.Exec(ctx, string(dumpSQL))
	require.NoError(t, err, "sequence dump must restore into a clean database:\n%s", dumpSQL)
	reappliedObjects, err := db.NewCatalog(pool).ExtractAllObjects(ctx, []string{"public"}, nil)
	require.NoError(t, err)
	reappliedMap, err := objectmap.Build(reappliedObjects)
	require.NoError(t, err)
	roundTrip, err := differ.NewDiffer().Diff(originalMap, reappliedMap)
	require.NoError(t, err)
	require.True(t, roundTrip.IsEmpty(), "restored sequence dump must round-trip exactly: creates=%v drops=%v alters=%v", roundTrip.ToCreate, roundTrip.ToDrop, roundTrip.ToAlter)
}

func assertOwnedSequenceDumpOrderForNames(t *testing.T, ddl, sequence, table string) {
	t.Helper()
	sequenceCreate := `CREATE SEQUENCE "public"."` + sequence + `"`
	tableCreate := `CREATE TABLE "public"."` + table + `"`
	ownedBy := `ALTER SEQUENCE "public"."` + sequence + `" OWNED BY "public"."` + table + `"."id";`
	sequenceIndex := strings.Index(ddl, sequenceCreate)
	tableIndex := strings.Index(ddl, tableCreate)
	ownedByIndex := strings.Index(ddl, ownedBy)
	require.NotEqual(t, -1, sequenceIndex, ddl)
	require.NotEqual(t, -1, tableIndex, ddl)
	require.NotEqual(t, -1, ownedByIndex, ddl)
	require.Less(t, sequenceIndex, tableIndex)
	require.Less(t, tableIndex, ownedByIndex)
}
