package parser

import (
	"testing"

	"github.com/jackhodkinson/schemata/pkg/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIdentitySequenceNameAndDescendingDefaultsArePreserved(t *testing.T) {
	t.Parallel()

	objects, err := NewParser().ParseSQL(`
		CREATE TABLE "Tenant".items (
			id integer GENERATED ALWAYS AS IDENTITY (
				SEQUENCE NAME "Tenant"."Custom IDs"
				INCREMENT BY -1
				NO MINVALUE
				NO MAXVALUE
			)
		);
	`)
	require.NoError(t, err)

	table := objects[schema.ObjectKey{Kind: schema.TableKind, Schema: "Tenant", Name: "items"}].Payload.(schema.Table)
	require.Len(t, table.Columns, 1)
	assert.True(t, table.Columns[0].NotNull, "identity columns are implicitly NOT NULL")
	require.NotNil(t, table.Columns[0].Identity)
	identity := table.Columns[0].Identity
	require.NotNil(t, identity.SequenceName)
	assert.Equal(t, schema.QualifiedName{Schema: "Tenant", Name: "Custom IDs"}, *identity.SequenceName)
	assert.Equal(t, []schema.SequenceOption{{Type: "INCREMENT BY", Value: -1, HasValue: true}}, identity.SequenceOptions)
}

func TestIdentitySequenceNameDefaultsToTableSchema(t *testing.T) {
	t.Parallel()

	objects, err := NewParser().ParseSQL(`
		CREATE TABLE tenant.items (
			id integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME custom_ids)
		);
	`)
	require.NoError(t, err)

	table := objects[schema.ObjectKey{Kind: schema.TableKind, Schema: "tenant", Name: "items"}].Payload.(schema.Table)
	require.NotNil(t, table.Columns[0].Identity)
	require.NotNil(t, table.Columns[0].Identity.SequenceName)
	assert.Equal(t, schema.QualifiedName{Schema: "tenant", Name: "custom_ids"}, *table.Columns[0].Identity.SequenceName)
}

func TestDuplicateIdentityOptionsFailClosed(t *testing.T) {
	t.Parallel()

	_, err := NewParser().ParseSQL(`
		CREATE TABLE public.items (
			id integer GENERATED ALWAYS AS IDENTITY (CACHE 2 CACHE 3)
		);
	`)
	require.Error(t, err)
	assert.Contains(t, err.Error(), `identity option "cache" is specified more than once`)
}
