//go:build integration
// +build integration

package integration

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/jackhodkinson/schemata/internal/differ"
	"github.com/jackhodkinson/schemata/internal/parser"
	"github.com/jackhodkinson/schemata/internal/planner"
	"github.com/jackhodkinson/schemata/pkg/schema"
	"github.com/stretchr/testify/require"
)

// generateDDLFromSchema takes a schema definition, runs it through the parser/differ/DDL generator pipeline,
// and returns the emitted DDL for comparison in the regression tests below.
func generateDDLFromSchema(t *testing.T, schemaSQL string) string {
	t.Helper()

	tmpDir := t.TempDir()
	schemaFile := filepath.Join(tmpDir, "schema.sql")
	err := os.WriteFile(schemaFile, []byte(schemaSQL), 0o644)
	require.NoError(t, err)

	p := parser.NewParser()
	desired, err := p.ParseFile(schemaFile)
	require.NoError(t, err)

	d := differ.NewDiffer()
	diff, err := d.Diff(desired, schema.SchemaObjectMap{})
	require.NoError(t, err)

	gen := planner.NewDDLGenerator()
	out, err := gen.GenerateDDL(diff, desired)
	require.NoError(t, err)

	return out
}

func TestGeneratedDDLMissingConstraintOptions(t *testing.T) {
	ddl := generateDDLFromSchema(t, `
CREATE TABLE public.orders (
	id BIGINT PRIMARY KEY,
	customer_id BIGINT,
	code TEXT,
	CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
		REFERENCES public.customers (id) MATCH FULL
		ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT orders_code_key UNIQUE (code) DEFERRABLE INITIALLY DEFERRED
);
`)

	require.Contains(t, ddl, "MATCH FULL", "foreign key MATCH mode should be preserved in generated DDL")
	require.Contains(t, ddl, "DEFERRABLE INITIALLY DEFERRED", "deferrability flags should be preserved on constraints")
}

func TestGeneratedDDLIncludesColumnDefaults(t *testing.T) {
	ddl := generateDDLFromSchema(t, `
CREATE TABLE public.events (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMPTZ DEFAULT now(),
	status TEXT DEFAULT 'pending'
);
`)

	require.Contains(t, ddl, "DEFAULT now()", "column default expressions should appear in CREATE TABLE DDL")
	require.Contains(t, ddl, "DEFAULT 'pending'", "string literal defaults should round-trip")
}

func TestGeneratedDDLMissingIdentityOptions(t *testing.T) {
	ddl := generateDDLFromSchema(t, `
CREATE TABLE public.ident_tests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
	code TEXT
);
`)

	require.Contains(t, ddl, "GENERATED BY DEFAULT AS IDENTITY", "identity columns should retain their identity clause")
	require.Contains(t, ddl, "START WITH 100", "identity sequence options should be included in generated DDL")
	require.Contains(t, ddl, "INCREMENT BY 10", "identity sequence options should be included in generated DDL")
}

func TestGeneratedDDLMissingIndexMetadata(t *testing.T) {
	ddl := generateDDLFromSchema(t, `
CREATE TABLE public.books (
	id SERIAL PRIMARY KEY,
	title TEXT,
	published_at TIMESTAMPTZ
);

CREATE INDEX idx_books_title ON public.books USING btree ((lower(title)) COLLATE "en_US" text_pattern_ops DESC NULLS LAST)
	WHERE (published_at IS NOT NULL);
`)

	require.Contains(t, ddl, `COLLATE "en_US"`, "index key collation should be emitted")
	require.Contains(t, ddl, "text_pattern_ops", "index operator classes should be emitted")
	require.Contains(t, ddl, "NULLS LAST", "index nulls ordering should be emitted")
	require.Contains(t, ddl, "WHERE (published_at IS NOT NULL)", "partial index predicates should round-trip")
}

func TestGeneratedDDLMissingTableReloptionsAndComments(t *testing.T) {
	ddl := generateDDLFromSchema(t, `
CREATE TABLE public.storage (
	id SERIAL PRIMARY KEY
) WITH (fillfactor=70, autovacuum_analyze_scale_factor=0.2);

COMMENT ON TABLE public.storage IS 'Stores document blobs';
`)

	require.Contains(t, ddl, "WITH (autovacuum_analyze_scale_factor=0.2, fillfactor=70)", "table reloptions should be preserved in CREATE TABLE DDL")
	require.Contains(t, ddl, "COMMENT ON TABLE public.storage IS 'Stores document blobs';", "table comments should be emitted alongside CREATE TABLE output")
}
