//go:build integration
// +build integration

package integration

import (
	"context"
	"testing"

	"github.com/jackhodkinson/schemata/internal/config"
	"github.com/jackhodkinson/schemata/internal/db"
	"github.com/jackhodkinson/schemata/internal/differ"
	"github.com/jackhodkinson/schemata/internal/parser"
	"github.com/jackhodkinson/schemata/pkg/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSequenceCatalogFidelityRoundTrip(t *testing.T) {
	ctx := context.Background()
	dbURL := devDBURL
	pool, err := db.Connect(ctx, &config.DBConnection{URL: &dbURL})
	require.NoError(t, err)
	t.Cleanup(pool.Close)

	const schemaName = "schemata_sequence_fidelity"
	_, err = pool.Exec(ctx, `DROP SCHEMA IF EXISTS schemata_sequence_fidelity CASCADE; CREATE SCHEMA schemata_sequence_fidelity;`)
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = pool.Exec(context.Background(), `DROP SCHEMA IF EXISTS schemata_sequence_fidelity CASCADE`)
	})

	source := `
		CREATE TABLE schemata_sequence_fidelity.identity_items (
			named_id integer GENERATED ALWAYS AS IDENTITY (
				SEQUENCE NAME schemata_sequence_fidelity.custom_identity_ids
				START WITH 41
				INCREMENT BY 7
				CACHE 3
				CYCLE
			),
			descending_id integer GENERATED BY DEFAULT AS IDENTITY (
				INCREMENT BY -1
			)
		);

		CREATE SEQUENCE schemata_sequence_fidelity.custom_ids AS bigint
			START WITH 9
			INCREMENT BY 2
			CACHE 5
			CYCLE;
		CREATE TABLE schemata_sequence_fidelity.explicit_items (
			id integer DEFAULT nextval('schemata_sequence_fidelity.custom_ids'::regclass)
		);
		ALTER SEQUENCE schemata_sequence_fidelity.custom_ids
			OWNED BY schemata_sequence_fidelity.explicit_items.id;
		COMMENT ON SEQUENCE schemata_sequence_fidelity.custom_ids IS 'custom sequence metadata';
		GRANT SELECT, UPDATE, USAGE ON SEQUENCE schemata_sequence_fidelity.custom_ids TO postgres;
		GRANT SELECT ON SEQUENCE schemata_sequence_fidelity.custom_ids TO PUBLIC;
	`

	desired, err := parser.NewParser().ParseSQL(source)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, source)
	require.NoError(t, err)

	objects, err := db.NewCatalog(pool).ExtractAllObjects(ctx, []string{schemaName}, excludedCatalogSchemas())
	require.NoError(t, err)

	var identityTable *schema.Table
	var explicitTable *schema.Table
	var explicitSequence *schema.Sequence
	for _, object := range objects {
		switch value := object.(type) {
		case schema.Table:
			table := value
			switch value.Name {
			case "identity_items":
				identityTable = &table
			case "explicit_items":
				explicitTable = &table
			}
		case schema.Sequence:
			sequence := value
			assert.NotEqual(t, "custom_identity_ids", value.Name, "identity backing sequences must be represented by their columns")
			assert.NotEqual(t, "identity_items_descending_id_seq", value.Name, "generated identity backing sequences must not leak as standalone objects")
			if value.Name == "custom_ids" {
				explicitSequence = &sequence
			}
		}
	}

	require.NotNil(t, identityTable)
	require.Len(t, identityTable.Columns, 2)
	namedIdentity := identityTable.Columns[0]
	require.NotNil(t, namedIdentity.Identity)
	require.NotNil(t, namedIdentity.Identity.SequenceName)
	assert.Equal(t, schema.QualifiedName{Schema: schemaName, Name: "custom_identity_ids"}, *namedIdentity.Identity.SequenceName)
	assert.Equal(t, []schema.SequenceOption{
		{Type: "START WITH", Value: 41, HasValue: true},
		{Type: "INCREMENT BY", Value: 7, HasValue: true},
		{Type: "CACHE", Value: 3, HasValue: true},
		{Type: "CYCLE"},
	}, namedIdentity.Identity.SequenceOptions)

	descendingIdentity := identityTable.Columns[1]
	require.NotNil(t, descendingIdentity.Identity)
	require.NotNil(t, descendingIdentity.Identity.SequenceName)
	assert.Equal(t, []schema.SequenceOption{{Type: "INCREMENT BY", Value: -1, HasValue: true}}, descendingIdentity.Identity.SequenceOptions)

	require.NotNil(t, explicitTable)
	require.Len(t, explicitTable.Columns, 1)
	assert.Equal(t, schema.TypeName("integer"), explicitTable.Columns[0].Type)
	require.NotNil(t, explicitTable.Columns[0].Default, "a noncanonical owned sequence must retain the table default")
	assert.Contains(t, string(*explicitTable.Columns[0].Default), "custom_ids")

	require.NotNil(t, explicitSequence, "a custom owned sequence must remain an explicit schema object")
	assert.Equal(t, "bigint", explicitSequence.Type)
	assert.Equal(t, int64(9), *explicitSequence.Start)
	assert.Equal(t, int64(2), *explicitSequence.Increment)
	assert.Equal(t, int64(5), *explicitSequence.Cache)
	assert.True(t, explicitSequence.Cycle)
	assert.Equal(t, &schema.SequenceOwner{Schema: schemaName, Table: "explicit_items", Column: "id"}, explicitSequence.OwnedBy)
	require.NotNil(t, explicitSequence.Comment)
	assert.Equal(t, "custom sequence metadata", *explicitSequence.Comment)

	actual, err := buildObjectMapFromObjects(objects)
	require.NoError(t, err)
	roundTrip, err := differ.NewDiffer().Diff(desired, actual)
	require.NoError(t, err)
	require.True(t, roundTrip.IsEmpty(), "sequence catalog round-trip must be empty: creates=%v drops=%v alters=%v", roundTrip.ToCreate, roundTrip.ToDrop, roundTrip.ToAlter)
}
